auth_jwt_expiry: 15m
auth_jwt_refresh_expiry: 1h
auth_jwt_secret: random
auth_login_token_expiry: 11m
auth_login_token_length: 8
auth_login_url: http://localhost:3001/login
database_url: postgres://user:password@localhost:5432/alumni?sslmode=disable
db_debug: false
log_level: debug
port: localhost:3001
